
app:
  # build: .
  image: ongoworks/launchdock2:latest
  links:
    - mongo
  ports:
    - "80:80"
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://mongo:27017/myapp"

mongo:
  image: mongo:latest
  command: mongod --smallfiles --storageEngine=wiredTiger