# used for CircleCI curl tests

launchdock:
  image: launchdock
  links:
    - mongo
  ports:
    - "80:80"
  environment:
    ROOT_URL: "http://localhost"
    MONGO_URL: "mongodb://mongo:27017/launchdock"

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
